services:
  dind:
    image: docker:26-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    command: ["--host=tcp://0.0.0.0:2375", "--log-level=error"]
    volumes:
      - dind-data:/var/lib/docker
    healthcheck:
      test: ["CMD", "docker", "version", "--format", "'{{.Server.Version}}'"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build: ./web
    environment:
      - ASPNETCORE_URLS=http://+:8024
      - DOCKER_HOST=tcp://dind:2375
    depends_on:
      dind:
        condition: service_healthy
    ports:
      - "8024:8024"

volumes:
  dind-data:
